# Site settings
title: FoffOCD
header-img: img/squiggles2.jpg
email: 
copyright_name: FoffOCD
description: ""
baseurl: ""
url: "http://www.foffocd.com"
twitter_username: itsakettle
github_username:  
facebook_username:  
email_username:  foffocd@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Other stuff 
permalink: /:title
